baseURL = "https://gobarules.github.io/geo8page/"
languageCode = "en-us"
title = "Testing page"
theme = "simple-landing"

[params]
  logo = "images/placeholder.png"
  sections = ["products", "ideas", "about", "contact"]
